### ISSUE TITLE
Why aren't you using AngularJS Client SDK?

### ISSUE THREAD

**Issue by spdaly** [ISBX/isbx-loopback-cms#22]
Not an issue - more of a question. I like the idea of the API helper, but wondering why you chose not to use the Loopback AngularJS Client SDK code?  Wouldn't that provide a cleaner implementation?

**Comment by tma-isbx** [comment]
1. Internally, we weren't fans of ngResource, and used mostly with $http and plain Javascript objects with a service similar to the services found in the project. Some reasons for this: really, really old versions of ngResource did not support promises; our endpoints though mostly REST-ful were not usually pure REST; sometimes we wanted do something with the data before or after the request. This is probably less of a concern for the CMS, though we have some instances with more customized forms/interactions that needed more flexible API interactions.

2. For the CMS specifically:
  1. One of our goals when building it as an npm module was to be as "plug and play" as possible. Requiring a build step to generate the lb-services.js seemed counter to this goal.
  2. Provider resolution in the controller and usage within the controller seems tricker. Example: specifying that our list controller in one instance is displaying Posts and depends on a PostProvider so that it can call Post.find(), but in another instance is displaying Users and depends on a UserProvider so that it can call User.find().

3. For our other Loopback projects (non-CMS related), we generally avoid using the client libraries for the various platforms mainly because we try to avoid having the filter specifications on the client side, and instead would create custom remoteMethods. Example: we would have a Posts/popular remote method instead of doing something like Posts?filter[order]='likes DESC'. This focus on "what we want" instead of "how" allows us to change the "how" on the serverside without having to update the clients (maybe adding support for soft delete or moderation requires us to change how we filter).

  We also try to lock down our remote methods, as we try to view our API consumers as potentially hostile, and exposing filters to the client potentially leaks information and provides an avenue to perform a denial of service.


So... some historical apathy towards ngResource, some CMS goals, and the fact that we weren't using it with our other projects.

For custom pages added to the CMS, it is definitely possible to add your own lbServices and make use of it.

**Comment by spdaly** [comment]
@tma-isbx Thanks for the time taken and detail provided in your response.  I have only been working with AngularJS for a year or so and Loopback for 3-4 months.  The insight you provided will help me move my project forward.  I was struggling with the "black box" type of approach lbServices implements.
