### ISSUE TITLE
Clearer contribution guidelines?

### ISSUE THREAD

**Issue by npedrini** [ISBX/isbx-loopback-cms#23]
First off, let me restate that this project is great. The company I work for plans to leverage it heavily for a project of our own, so thank you for all the work that's gone into getting it this far.

That said, there is a good bit of functionality we'd like to add, and it would be great to get some guidance on the most effective way to contribute, get those changes rolled back into master, and what we can reasonably expect that process to look like.

There are a handful of pull requests that go back to July, for example, but they all seem to be pending. I understand triaging/commenting on pull requests can be time consuming, and that that time probably never really exists, but I just want to get a better sense of what contributors can expect as far as how we can help the project continue to grow. Thanks!

**Comment by coolwr** [comment]
Hi Noah! Glad you guys find the project valuable. We've been using the CMS on several of our client projects over the last year ranging from small to large scale enterprise deployments. We've learned a lot and we're planning the next iteration this year. We are exploring refactoring several aspects of the CMS and also making enhancements to key areas. We are planning on continuing to support the current feature set and improving on them overtime as well as keeping things backwards compatible.

We do need to spend a bit of time looking at the past pull requests and getting some of that cleaned up. We are more than happy to collaborate with you and your team on improving what we have today. Let me know what features you are interested in adding. We've built several add-ons outside of the project that we've been meaning on integrating as well.

**Comment by npedrini** [comment]
Thanks @coolwr. I'm still orienting myself to the project, but most of my attention has been on the CMS. Based on our needs, here are a few features I've identified as things we'd love to get added:

1. Additional field types
  - Video field, with S3 support (similar to Image)
  - Geopoint field (with map-based UI for setting lat/lng value)
2. Model relations
  - At a minimum, ability to list a model's relations when editing and either be able to add/remove/edit inline or link to the corresponding model's edit page, if available
3. Fully implement "view" route
  - Looks like there is some scaffolding for this, but a route for viewing read-only models would be helpful
4. Documentation: There is a lot of great customizability in here already, but a lack of documentation around all the config parameters and what they do. This is something we could definitely help with.

I also noticed a few areas for potential improvement around caching:
- Move local storage reads/writes to a service, and handle write requests that exceed quota (currently they seem to generate an irrecoverable error)
- Don't re-request a model list if request is cached (unless I'm missing something, ModelList.loadItems() sends a request even if its found in the cache)
- Create cache keys by concatenating model name and route or equivalent scheme, so that they can easily be cleared as relevant add/edit/remove operations happen

I'll add any other ideas for potential features based on our use cases as they come up. 

As far as embarking on some of this, but wanting to contribute back to the core, would it be best to continue submitting feature-based pull requests? I don't want to inundate the approval queue, but on the flipside, from my experience the further a fork and upstream diverge the harder it is to discreetly merge in specific features.

**Comment by coolwr** [comment]
Great points. We'd love to get your development support on further enhancing the capabilities of the CMS and we welcome contributions the core of the project. My recommendation is to start with some "bite-size" contributions so we can have faster review and merge cycles rather than lengthy back and forth.

Here's some feedback on your requests:

**Additional Field Types**
We are working on a `ModelFieldVideo` directive that will be ready within the next 2 weeks that is similar to the `ModelFieldImage` directive in using AWS S3 for storage. 

As for the Geopoint field we a pull-request in branch `feature/model-field-location` that should should get merged in this week, which will introduce the `ModelFieldLocation` directive for searching google maps and picking a location. You can pass in a place type via a configuration parameter to limit the filters on what is searchable. There's probably going to be a lot more functionality you may need here and I think would be a good contribution point.

**Model Relations**
It would be interesting to explore this further with you and see what you had in mind in terms of viewing relationships and linking to them. We do have a `ModelFieldReference` directive that allows one-to-many or many-to-many relationship management, but not sure if that meets your needs (https://github.com/ISBX/isbx-loopback-cms/wiki/Customizing-the-Model-Edit-View#multi-reference-field)

**Fully Implemented "view" route**
We initially had the idea of a view and edit route for each of the directives, but decided that this is where custom controllers would come in when we needed custom views to display content. Let me know if you have other thoughts. https://github.com/ISBX/isbx-loopback-cms/wiki/Custom-Modules

**Support for non-standard Model requests/responses**
We completely agree that we don't like loopback's `filter` implementation and have moved away from it in our own projects. We do, however, find it useful in the CMS to get some basic CRUD functionality working quickly. You can call custom loopback remote methods by using an `api` property and specifying the URI to your remote method. There's an example in our Wiki on setting up management of user roles where we use the `api` property and you can specify dynamic path variables in the URI. https://github.com/ISBX/isbx-loopback-cms/wiki/Installing-the-ISBX-CMS

**Documentation**
Yes, one of our new year's resolution this year is to add more documentation around all of the config.json parameters as well as other undocumented CMS capabilities. We also want to put together a sample project demonstrating all of the features.  Any documentation support you can provide in our Wiki would be awesome!

**Caching**
Yes, I agree, we should move away from the localStorage cache as well as your other comments. 

Thanks for all of the feedback. I'll keep you posted later this week as we get the `ModelFieldVideo` and `ModelFieldLocation` directives merged in. We'll also clean up the pull requests too. Let me know if you and your team want to get on the phone to further the discussion and see where you guys can jump in and contribute.

**Comment by npedrini** [comment]
Awesome, thanks for the detailed response!

I look forward to video and location fields being merged in. I created a quick and dirty [ModelVideoField](https://github.com/npedrini/isbx-loopback-cms/tree/feature/model-edit-video-field) as well based on ModelImageField today. One thing I needed to add is the ability to set a custom S3 filename, so in my implementation display.options.name is used if set and can include tokens for inserting the uuid and file extension.

With model relations, I guess I'm a little unclear how to add them to the edit view since ModelEdit seems to build the UI purely from the model's property definitions, whereas relations are stored elsewhere as you know, but will look into it more. Entirely possible I'm missing something here though.

I haven't explored building any views off of custom controllers, but its good to know that a readonly view is a potential use case. It might be nice to include a default read-only view as well, though low priority. I'm sure I can throw one together easy enough by duplicating and whittling down ModelEdit.

Thanks again.
