### ISSUE TITLE
Error saving model

### ISSUE THREAD

**Issue by sander48k** [ISBX/isbx-loopback-cms#8]
I have successfully integrated the cms (version 0.0.14) in my loopback project (loopback version 2.22.0). I am able to add some models and list them in the cms backend. However, when I try to add a model instance, e.g. a User, from the web interface i get the following message:

TypeError: Cannot read property '__model' of undefined

This error originates in index.js on line 296, i.e.:

```
  app.put('/model/save', function(req, res) {
    //TODO: validate access token and ACL
    var data = req.body;
    relationalUpsert.upsert(data, function(error, response)
```
It seems that body is undefined. Any idea?

**Comment by coolwr** [comment]
Can you check your /server/server.js and make sure you have the following body parsing defined:

```
var bodyParser = require('body-parser');
...
app.use(loopback.compress());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.text());
```

**Comment by sander48k** [comment]
Thanks for the swift response. I configured body-parser (in middleware.json) and now I am able to save models. Great!

For this to work I also had to install body-parser as a dependency of my project, which feels a bit strange because loopback has it's own body-parser module.

It also seems a bit odd that body-parser isn't configured by default. How does the API explorer process request bodies? Am I missing something?

**Comment by coolwr** [comment]
Thats correct, loopback node module itself has its own body parser in its
rest api component; however, the body parser is not applied at the main web
server component at the root of the application by default. I think this
was intentional so that you have the flexibility to add it or not for your
primary application.

We previously were using the built-in loopback rest save (upsert) api when
saving model data, but later wrote our own relational upsert api to handle
hierarchical saving of data when using the CMS. For example, if you wanted
to save a User model along with a Profile photo in a separate reference
table you can do it in one rest api call rather than 2.

I'll create a wiki page later today and send you the link once it's up on
how to use the various CMS controls we created for reference fields, file
upload, image upload, date/time, multi-select, drop downs, checkboxes,
sliders, and the WYSIWYG editor. The reference field is useful for handling
relational data in a one-to-many or many-to-many situation.

--kelly

**Comment by sander48k** [comment]
Thanks! Keep up the good work!

**Comment by coolwr** [comment]
We just posted up a work-in-progress Wiki page describing the various
controls/field types available for you to incorporate into your LoopBack
Model JSON:

https://github.com/ISBX/isbx-loopback-cms/wiki/Customizing-the-Model-Edit-View
